### ISSUE TITLE
Auto Width

### ISSUE THREAD

**Issue by rjshreve** [CreativeIT/getmdl-select#10]
A nice feature may be for the field/dropdown to auto adjust width to the widest LI so options don't get cut off! Great project! So thankful to have found it!

**Comment by randrianov** [comment]
@rjshreve Thanks for nice advice, will add soon

**Comment by mibamur** [comment]
+ 1

**Comment by randrianov** [comment]
@mibamur thanks, hope will fix soon

**Comment by franckevva** [comment]
Hey! You can update getmdl-select and try it now. 
I add auto width based on the maximum element in the menu list

**Comment by Ephphatha** [comment]
The auto-width overrides any pre-existing width set on the element which can cause layout issues. It would be nice if this behaviour could be toggled (make it apply to an alternate class?), for now I've altered the code to set a min-width instead since the pre-existing width is wider in my use case.
